project_id = "amzlrrrhjsqjndbrdume"

[functions.research-async]
verify_jwt = false

[functions.scihub-download]
verify_jwt = false

[functions.chat-papers]
verify_jwt = false

[functions.synthesize-papers]
verify_jwt = false

[functions.add-study]
verify_jwt = false

[functions.coci]
verify_jwt = false
